-- comment
CREATE TABLE [NewExtranetDB].[dbo].[PublicApiUser] (
  Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  ApiKey NVARCHAR(50) NOT NULL UNIQUE,
  Email NVARCHAR(320) NOT NULL UNIQUE,
  SiteUserId INT NOT NULL CONSTRAINT FK_SiteUserId FOREIGN KEY REFERENCES SiteUser(uid)
);
